name: cake_by_mommy
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  shared_preferences: ^2.2.2
  dio: ^5.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.1.0
  supabase_flutter: ^2.3.4
  image_picker: ^1.0.7
  flutter_dotenv: ^6.0.0
  geolocator: ^11.1.0
  location: ^6.0.0
  permission_handler: ^11.3.1
  flutter_map: ^7.0.0
  latlong2: ^0.9.0
  url_launcher: ^6.1.10
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  cached_network_image: ^3.3.1 
  path_provider: ^2.1.5
  flutter_native_splash: ^2.4.3 # <-- SUDAH PINDAH KE SINI (BENAR)
  connectivity_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  font_awesome_flutter: ^10.7.0
  # flutter_native_splash SUDAH DIHAPUS DARI SINI (BENAR)

# KONFIGURASI NATIVE SPLASH
flutter_native_splash:
  color: "#fde8cb"
  image: assets/images/logo.png
  android_12:
    image: assets/images/logo.png
    icon_background_color: "#fde8cb"
  fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/browniescup.png
    - assets/images/kastengel.png
    - assets/images/lidahkucing.png
    - assets/images/nastar.png
    - assets/images/palmcheese.png
    - assets/images/putrisalju.png
    - assets/images/sagukeju.png
    - assets/images/thumbrin.png
    - assets/images/bg.png
    - assets/images/logo.png